export const CREATE = "CREATE";
export const UPDATE = "UPDATE";
export const DELETE = "DELETE";
export const FETCH_ALL = "FETCH_ALL";
export const FETCH_ALL_TAG = "FETCH_ALL_TAG";
export const FETCH_ALL_SEARCH = "FETCH_ALL_SEARCH";
export const FETCH_NEW_POSTS_NOTIFICATIONS = "FETCH_NEW_POSTS_NOTIFICATIONS";
export const DELETE_NOTIFICATION_AFTER_CLICK = "DELETE_NOTIFICATION_AFTER_CLICK";
export const LIKE = "LIKE";
export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";
export const CREATE_LOG = "CREATE_LOG";
export const GET_LAST_NOTIFICATION_LOG = "GET_LAST_NOTIFICATION_LOG";
export const SOCKET_ON = "SOCKET_ON";
export const ADD_RECIEVED_NOTIFICATION = "ADD_RECIEVED_NOTIFICATION";

